apiVersion: v1
kind: Service
metadata:
  name: nginx-preview
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30100  # ローカルホストでアクセスするポート（範囲：30000-32767）
  selector:
    app: nginx
