apiVersion: v1
kind: Service
metadata:
  name: nginx-active
  namespace: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080 #ローカルアクセス用ポート 
  selector:
    app: nginx
