apiVersion: v1
kind: Service
metadata:
  name: nginx-preview
  namespace: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30100 #ローカルアクセス用ポート 
  selector:
    app: nginx
